# Generated by Django 6.0.4 on 2026-04-25 10:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('images', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('vues', models.IntegerField(default=0)),
                ('feeling', models.CharField(blank=True, default='', max_length=100)),
                ('localisation', models.CharField(blank=True, default='', max_length=200)),
                ('statut', models.CharField(choices=[('approuve', 'Approuvé'), ('en_attente', 'En attente'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'publications',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='api.publication')),
            ],
            options={
                'db_table': 'commentaires',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=100)),
                ('type_culture', models.CharField(max_length=100)),
                ('avatar', models.CharField(default='🌱', max_length=10)),
                ('bio', models.TextField(blank=True, default='')),
                ('cover_color', models.CharField(default='#1a4731', max_length=20)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('en_attente', 'En attente')], default='actif', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='following_set', to='api.user')),
                ('saved_posts', models.ManyToManyField(blank=True, related_name='saved_by', to='api.publication')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='api.commentaire')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='api.user')),
            ],
            options={
                'db_table': 'reponses',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='api.user'),
        ),
        migrations.AddField(
            model_name='publication',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_publications', to='api.user'),
        ),
        migrations.AddField(
            model_name='publication',
            name='partages',
            field=models.ManyToManyField(blank=True, related_name='shared_publications', to='api.user'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('like', 'Like'), ('commentaire', 'Commentaire'), ('follow', 'Follow'), ('partage', 'Partage'), ('nouveau_post', 'Nouveau post'), ('approbation', 'Approbation'), ('rejet', 'Rejet'), ('suspension', 'Suspension')], max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('lu', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.publication')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_recues', to='api.user')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_envoyees', to='api.user')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='commentaire',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='api.user'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_commentaires', to='api.user'),
        ),
    ]
